config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]

  get '/home/about', to: 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2,maximum: 20}
  validates :introduction, length: { maximum: 50}

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @book_show = Book.find(params[:id])
    @user = @book_show.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show

    @user = User.find(params[:id])
    @user_info = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(@user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th>
        <% if user.introduction.present? %>
        <%= user.introduction %>
        <% else %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<div class="row">
  <div class="container">
    <div class="row mt-4">
      <% unless user.guest_user? %>
        <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog", aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<p></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success"%>
        </div>
      <div>
      <%= link_to 'Show', book_path(@book.id) %>
      |
      <%= link_to 'Back', books_path %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'new', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |books| %>
          <tr>
            <td><%= link_to user_path(books.user_id) do %>
            <%= image_tag books.user.get_profile_image(100,100) %></td>
            <% end %>
            <td><%= link_to book_path(books.id) do %>
            <%= books.title %></td>
            <% end %>
            <td><%= books.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>New Book</h2>
<%= form_with model: @book do |f| %>
<div>
  <div><%= f.label :title, "Title" %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :body, "Opinion" %></div>
  <div><%= f.text_area :body %></div>
  <div><%= f.submit 'Create Book' %></div>
</div>
<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'new', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book_show.user_id) do %>
                <%= image_tag @book_show.user.get_profile_image(100,100) %><br>
                <%= @book_show.user.name %>
              <% end %>
            </tb>
            <td><%= link_to book_path(@book_show.id) do %>
            <%= @book_show.title %>
            <% end %>
            </td>
            <td>
              <%= @book_show.body %>
            </td>
            <td>
              <% if @book_show.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book_show.id), class: "btn btn-sm btn-success text-white" %>
              <% end %>
            </td>
            <td>
              <% if @book_show.user == current_user %>
                <%= link_to 'Destroy', book_path(@book_show.id), method: :delete, "data-confirm" => "本当に消しますか？",
                class: "btn btn-sm btn-danger text-white" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <div class="row">
        <span class="mx-auto"><h1>Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!</h1></span>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div>
  <%= flash[:notice] %>
  </div>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fa-solid fa-book" aria-hidden="true"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, class: 'btn btn-secondary btn-sm btn-block mb-3 sign_in', method: :post %>
          </div>
          <div class="row">
            <%= link_to new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3' do %>
            Log in
            <% end %>
          </div>
          <div class="row">
            <%= link_to new_user_registration_path, class: 'btn btn-success btn-sm btn-block' do %>
            Sign up
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7377292350.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home" aria-hidden="true"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users" aria-hidden="true"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open" aria-hidden="true"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home" aria-hidden="true"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link" aria-hidden="true"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus" aria-hidden="true"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt" aria-hidden="true"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <p class="mx-auto">CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, "Image" %>
          <%= f.file_field :profile_image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_area :introduction, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/new', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100, 100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/new', book: @book, user: @user_info %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %></td>
            <% end %>
            <td><%= link_to book_path(book.id) do %>
            <%= book.title %></td>
            <% end %>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>